baseURL = "https://mutualismaccord.org"
locale = "en-us"
title = "Mutualism Accord"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Manifesto"
    url = "posts/manifesto.md"
    weight = 10

  [[menu.main]]
    name = "Technical Spec"
    url = "posts/spec.md"
    weight = 20

