# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Terri Clark / TREE(3) Vocations, LLC

baseURL = "https://mutualismaccord.org"
locale = "en-us"
title = "Mutualism Accord"
theme = "PaperMod"

# This forces Hugo to completely ignore the broken RSS file
disableKinds = ["RSS"]

[params]
  homeInfoParams = { title = "The Mutualism Accord", content = "A universal, open-source protocol framework to dismantle the digital oligarchy." }

[menu]
  [[menu.main]]
    name = "Read Manifesto"
    url = "/posts/manifesto/"
    weight = 10

  [[menu.main]]
    name = "Technical Specification"
    url = "/posts/spec/"
    weight = 20
