baseURL = "https://mutualismaccord.org/"
languageCode = "en-us"
title = "Mutualism Accord"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = 'Manifesto'
    pageRef = '/posts/manifesto'
    weight = 10
  [[menu.main]]
    name = 'Technical Spec'
    pageRef = '/posts/spec'
    weight = 20
